apiVersion: apps/v1
kind: Deployment
metadata:
  name: exoplanet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exoplanet-finder
  template:
    metadata:
      labels:
        app: exoplanet-finder
    spec:
      containers:
        - name: exoplanet-finder
          image: exoplanet-finder:latest
          ports:
            - containerPort: 2222